In [1]:

import sys
import os
sys.path.append(os.path.abspath(".."))
from src.kMeans import kmeans

data_points = [
    [1.0, 2.0],
    [1.5, 1.8],
    [5.0, 8.0],
    [8.0, 8.0],
    [1.0, 0.6],
    [9.0, 11.0],
    [4.0, 5.0], 
    [6.0, 5.5]   
]
k = 2
kmeans(data_points, k,10)

Iteration # 1
Data Points:
 [[ 1.   2. ]
 [ 1.5  1.8]
 [ 5.   8. ]
 [ 8.   8. ]
 [ 1.   0.6]
 [ 9.  11. ]
 [ 4.   5. ]
 [ 6.   5.5]]
Cluster Assignments: [1 0 0 0 0 0 0 0]
Centroids:
 [[1.5 1.8]
 [1.  2. ]]

Iteration # 2
Data Points:
 [[ 1.   2. ]
 [ 1.5  1.8]
 [ 5.   8. ]
 [ 8.   8. ]
 [ 1.   0.6]
 [ 9.  11. ]
 [ 4.   5. ]
 [ 6.   5.5]]
Cluster Assignments: [1 1 0 0 1 0 0 0]
Centroids:
 [[4.92857143 5.7       ]
 [1.         2.        ]]



(array([[6.4       , 7.5       ],
        [1.16666667, 1.46666667]]),
 array([1, 1, 0, 0, 1, 0, 0, 0]))

In [9]:
import src.kMeans
#print(dir(src.kMeans))
import src.kMeans
#print(src.kMeans.__file__)
import importlib
import src.kMeans

importlib.reload(src.kMeans)
import src.kMeans
print(open(src.kMeans.__file__).read())

import src.kMeans
print(dir(src.kMeans))


['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']


In [3]:
#Reading and saving into excel file
import numpy as np
import pandas as pd
import random
import math


import sys
import os
sys.path.append(os.path.abspath(".."))
from src.kMeans import kmeans


# Read Excel file
df = pd.read_excel("../data/k_mean_clustering.xlsx", engine="openpyxl")

# Extract x and y columns
data = df[['x', 'y']].values

k = 3   
centroids, cluster_assignments = kmeans(data, k)

# Write cluster assignments back to excel sheet
df.cluster = cluster_assignments
# Save updated Excel file
df.to_excel("k_mean_clustering.xlsx", index=False)

print("Clustering complete. Results written to k_mean_clustering.xlsx")
print("CENTROIDS :\n",centroids,"\nCLUSTER ASSIGNMENT \n",cluster_assignments)


Iteration # 1
Data Points:
 [[   1.2    3.4]
 [   2.1    2.9]
 [   3.5    4.2]
 [   4.     3.8]
 [   5.1    4.9]
 [   6.3    5.2]
 [   7.     6.1]
 [   8.2    6.5]
 [   9.1    7.3]
 [  10.     8. ]
 [  -1.5   -2.2]
 [  -2.3   -3.1]
 [  -3.8   -4. ]
 [  -4.5   -3.6]
 [  -5.2   -5.1]
 [  -6.    -5.8]
 [  -7.2   -6.4]
 [  -8.5   -7. ]
 [  -9.3   -7.8]
 [ -10.5   -8.6]
 [  -1.8   -3. ]
 [  -2.6   -2.7]
 [  -3.9   -4.5]
 [  -4.8   -3.9]
 [  -5.5   -5.3]
 [  -6.7   -5.9]
 [  -7.5   -6.7]
 [  -8.8   -7.2]
 [  -9.6   -8. ]
 [ -10.8   -8.9]
 [ 100.   200. ]
 [ 110.   190. ]
 [ 120.   210. ]
 [ 130.   220. ]
 [ 140.   230. ]
 [ 150.   240. ]
 [ 160.   250. ]
 [ 170.   260. ]
 [ 180.   270. ]
 [ 190.   280. ]
 [ 200.   300. ]
 [ 210.   310. ]
 [ 220.   320. ]
 [ 230.   330. ]
 [ 240.   340. ]
 [ 250.   350. ]
 [ 260.   360. ]
 [ 270.   370. ]
 [ 280.   380. ]
 [ 290.   390. ]
 [ 300.   400. ]
 [ 310.   410. ]
 [ 320.   420. ]
 [ 330.   430. ]
 [ 340.   440. ]
 [ 350.   450. ]
 [ 360.   460. ]
 [ 